# Generated by Django 5.1.15 on 2026-09-09 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('guidance_level', models.CharField(choices=[('direct', 'Pistas Diretas (Iniciação)'), ('subtle', 'Pistas Sutis (Intermediário)'), ('autonomous', 'Sem Pistas (Autonomia Real)')], default='direct', max_length=20)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['track', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('foundations', 'Fundações & Processos'), ('structure', 'Estrutura & Lógica Interna'), ('protocols', 'Protocolos & APIs'), ('automation', 'Automação & Engenharia'), ('specialties', 'Especialidades Técnicas')], default='foundations', max_length=30)),
                ('description', models.TextField()),
                ('mini_site_route', models.CharField(help_text='Rota do iframe sandboxed (ex: /mini-sites/manual-vault/)', max_length=200)),
                ('color_theme', models.CharField(default='default-track', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trilha',
                'verbose_name_plural': 'Trilhas',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: QA-MAN-012', max_length=30, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('target_element', models.CharField(blank=True, help_text='Seletor alvo sob teste (ex: input#user-age)', max_length=150)),
                ('oracle_description', models.TextField(help_text='Comportamento esperado / Critérios de aceite')),
                ('investigation_scope', models.TextField(help_text='O que o aluno vai investigar — NUNCA o que vai encontrar')),
                ('xp_reward', models.PositiveIntegerField(default=75)),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='curriculum.module')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('activity_type', models.CharField(choices=[('bug_hunt', 'Caça a Comportamentos / Interação'), ('bug_report', 'Escrita de Bug Report'), ('code_automation', 'Script de Automação (Playwright)'), ('unit_test', 'Teste Unitário'), ('sql_query', 'Consulta SQL')], default='bug_hunt', max_length=30)),
                ('instructions', models.TextField()),
                ('harness_code', models.TextField(blank=True, help_text='Suite oculta de validação para o Piston')),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='curriculum.topic')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['topic', 'order'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='curriculum.track'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('track', 'number')},
        ),
    ]
