# Generated by Django 5.1.15 on 2026-09-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='oracle_criteria',
            field=models.JSONField(blank=True, default=list, help_text='Critérios estruturados de aceite'),
        ),
    ]
