# Generated by Django 5.1.15 on 2026-09-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_topic_oracle_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('available', 'Disponivel'), ('frozen', 'Congelada'), ('in_construction', 'Em Construcao')], default='available', help_text='Estado de disponibilidade da trilha (available, frozen, in_construction)', max_length=30),
        ),
    ]
