# Generated by Django 5.1.15 on 2026-09-09 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_topic_oracle_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_seed', models.CharField(default='481029', max_length=64)),
                ('language', models.CharField(default='python', max_length=32)),
                ('code', models.TextField()),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('signal', models.CharField(blank=True, max_length=32, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('passed', 'Aprovado'), ('failed', 'Reprovado'), ('timeout', 'Tempo Limite Excedido'), ('memory_limit', 'Limite de Memória Excedido'), ('runtime_error', 'Erro de Execução')], default='failed', max_length=32)),
                ('tests_passed', models.IntegerField(default=0)),
                ('tests_total', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('threshold_applied', models.FloatField(default=70.0)),
                ('is_approved', models.BooleanField(default=False)),
                ('feedback_summary', models.TextField(blank=True)),
                ('feedback_hint', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='curriculum.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
