# Generated by Django 5.1.15 on 2026-09-09 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopedBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: VAL-AGE-001', max_length=40, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(help_text='Descrição do comportamento defeituoso ou anômalo')),
                ('severity', models.CharField(choices=[('blocker', 'Bloqueador (Blocker)'), ('critical', 'Crítico (Critical)'), ('major', 'Grave (Major)'), ('minor', 'Menor (Minor)'), ('trivial', 'Trivial (Trivial)')], default='major', max_length=20)),
                ('weight', models.PositiveIntegerField(default=10, help_text='Peso no sorteio determinístico por seed')),
                ('is_defect', models.BooleanField(default=True, help_text='True = bug/desvio de regra; False = comportamento correto de controle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='curriculum.topic')),
            ],
            options={
                'verbose_name': 'Comportamento Escopado',
                'verbose_name_plural': 'Comportamentos Escopados',
                'ordering': ['topic', 'code'],
            },
        ),
    ]
