# Generated by Django 5.1.15 on 2026-09-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopedbehavior',
            name='actual_behavior',
            field=models.TextField(blank=True, help_text='Comportamento desviante/defeituoso observado'),
        ),
        migrations.AddField(
            model_name='scopedbehavior',
            name='category',
            field=models.CharField(default='boundary_validation', help_text='Ex: boundary_validation, input_sanitization', max_length=60),
        ),
        migrations.AddField(
            model_name='scopedbehavior',
            name='expected_behavior',
            field=models.TextField(blank=True, help_text='Comportamento esperado pelo oráculo'),
        ),
        migrations.AddField(
            model_name='scopedbehavior',
            name='hint_direct',
            field=models.TextField(blank=True, help_text='Pista direta (onboarding / nível direto)'),
        ),
        migrations.AddField(
            model_name='scopedbehavior',
            name='hint_subtle',
            field=models.TextField(blank=True, help_text='Pista sutil (nível intermediário)'),
        ),
        migrations.AddField(
            model_name='scopedbehavior',
            name='trigger_action',
            field=models.CharField(blank=True, default='submit_form', help_text='Ação disparadora (ex: submit_form, blur)', max_length=60),
        ),
        migrations.AddField(
            model_name='scopedbehavior',
            name='trigger_element',
            field=models.CharField(blank=True, help_text='Elemento CSS alvo (ex: input#user-age)', max_length=150),
        ),
        migrations.AddField(
            model_name='scopedbehavior',
            name='trigger_value',
            field=models.CharField(blank=True, help_text='Valor específico que dispara o comportamento', max_length=150),
        ),
        migrations.AlterField(
            model_name='scopedbehavior',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição do comportamento defeituoso ou anômalo'),
        ),
    ]
