# Generated by Django 5.1.15 on 2026-09-10 00:18

import apps.gamification.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_topic_oracle_criteria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('icon_symbol', models.CharField(default='🔍', max_length=16)),
                ('rarity', models.CharField(choices=[('common', 'Padrão'), ('notable', 'Notável'), ('rare', 'Raro'), ('chief_inspector', 'Inspetor-Chefe')], default='common', max_length=32)),
                ('xp_reward', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalystProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(blank=True, default='', help_text='Nome de campo do analista', max_length=64)),
                ('analyst_id', models.CharField(default=apps.gamification.models.generate_analyst_id, help_text='Identificador institucional único', max_length=32, unique=True)),
                ('total_xp', models.IntegerField(default=0, help_text='Experiência acumulada (começa estritamente em 0 para novos usuários)')),
                ('streak_enabled', models.BooleanField(default=True, help_text='Se o mecanismo de sequência de prática está ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('audit_submission', 'Submissão de Auditoria Manual'), ('code_verification', 'Verificação de Automação Sandboxed')], default='audit_submission', max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(db_index=True, help_text='Data local da submissão no fuso horário configurado (America/Sao_Paulo)')),
                ('is_approved', models.BooleanField(default=False, help_text='Se a submissão atingiu o limiar de aprovação')),
                ('score', models.FloatField(default=0.0)),
                ('reference_id', models.CharField(blank=True, help_text='ID da submissão de origem (Audit ou Code)', max_length=64)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_activities', to='curriculum.topic')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_activities', to='curriculum.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade de Prática',
                'verbose_name_plural': 'Atividades de Prática',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'date'], name='gamificatio_user_id_a4799d_idx'), models.Index(fields=['user', 'track', 'date'], name='gamificatio_user_id_2e73ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_context', models.JSONField(blank=True, default=dict)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_awards', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
