# Generated by Django 5.1.15 on 2026-09-10 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_topic_oracle_criteria'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystprofile',
            name='active_topic',
            field=models.ForeignKey(blank=True, help_text='Tópico de auditoria atualmente ativo no dossiê', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_analysts', to='curriculum.topic'),
        ),
    ]
